server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github-idp:
            provider: github
            # 使用环境变量的配置参数
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            client-name: learning-example
            # https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps
            scope:
              - repo
              - user
        provider:
          github:
            # https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps
            user-name-attribute: login
