server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github-idp:
            # 内置公共的provider，@see org.springframework.security.config.oauth2.client.CommonOAuth2Provider
            # 自动回调：http://127.0.0.1:8080/login/oauth2/code/github-idp，相关过滤器：OAuth2LoginAuthenticationFilter
            provider: github
            # 使用环境变量的配置参数
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            client-name: Sign in Github OAuth
            # https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps
            scope:
              - repo
              - user
        provider:
          github:
            # https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps
            user-name-attribute: login
